[build]
  base = "frontend"
  command = "printenv > .env && npm ci --include=optional && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"